root = "."
tmp_dir = ".tmp"

[build]
  bin = ".tmp/serve/dashboard"
  cmd = "make build-backend"
  delay = 2000
  exclude_dir = []
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "make run-backend"
  include_dir = ["src/app/backend"]
  include_ext = ["go"]
  kill_delay = "1s"
  log = "build-errors.log"
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true
